{% set name = "pytestify" %}
{% set version = "1.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytestify-{{ version }}.tar.gz
  sha256: ff2a69dc4987ae173f4301cf9225c7fb6c7d8492b9e422a62ee299881e9a10c6

build:
  number: 0
  noarch: python
  entry_points:
    - pytestify = pytestify._main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - tokenize-rt >=4.0.0

test:
  imports:
    - pytestify
    - pytestify.fixes
  commands:
    - pip check
    - pytestify --help
  requires:
    - pip

about:
  home: https://github.com/dannysepler/pytestify
  summary: Automatically convert unittests to pytest
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicoddemus
    - dannysepler
